;; -*- lexical-binding: t -*-
;; editing settings

(setq kill-ring-max 2000)
(setq column-number-mode t)
(setq-default indent-tabs-mode nil)
(setq-default tab-width 8)
(setq indent-line-function 'insert-tab)
(setq c-default-style "linux") 
(setq c-basic-offset 8) 
(c-set-offset 'comment-intro 0)
(global-font-lock-mode 1)
(setq font-lock-maximum-decoration t)
(setq search-highlight t)
(setq query-replace-highlight t)
(show-paren-mode t)
(setq show-paren-style 'parentheses)
;;(setq visible-bell t)
(setq ring-bell-function 'ignore)
(setq mouse-yank-at-point t)
(setq default-fill-column 76)
(setq enable-recursive-minibuffers t)
(setq backup-inhibited t)
(fset 'yes-or-no-p' y-or-n-p)
(setq dired-dwin-target t)
;; (global-set-key (kbd "C-x C-b") 'ibuffer)
;; (autoload 'ibuffer "ibuffer" "List buffers." t)
